apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: apollo-configservice-prod
  namespace: inc
  labels:
    wayne-app: apollo-configservice
    wayne-ns: inc
    app: apollo-configservice-prod
    inc-app: apollo-configservice
spec:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            topologyKey: kubernetes.io/hostname
            labelSelector:
              matchLabels:
                inc-app: apollo-configservice
  replicas: 3
  selector:
    matchLabels:
      app: apollo-configservice-prod
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        wayne-app: apollo-configservice
        wayne-ns: inc
        app: apollo-configservice-prod
    spec:
      volumes:
        - name: apollo-configservice-prod
          configMap:
            name: apollo-configservice-prod
            items:
              - key: application-github.properties
                path: application-github.properties
      containers:
        - name: apollo-configservice-prod
          image: >-
            your_registry/inc_img/apollo-configservice:v1.4.0
          securityContext:
            privileged: false
          imagePullPolicy: IfNotPresent
          ports:
            - protocol: TCP
              containerPort: 8080
          volumeMounts:
            - name: apollo-configservice-prod
              mountPath: /apollo-config-server/config/application-github.properties
              subPath: application-github.properties
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 10
            timeoutSeconds: 1
            failureThreshold: 10
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 1
            failureThreshold: 10
          env:
            - name: A