apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-metrics-grafana
  namespace: monitor
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  #nfs:
  #  server: 你的存储地址
  #  path: /pv-metrics-grafana
