apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-metrics-grafana
  namespace: monitor
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 10Gi

