apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-alertmanager-for-middleware
  namespace: monitoring 
spec:
  mountOptions:
    - vers=4.0
    - noresvport
  capacity:
      storage: 100Gi
  accessModes:
      - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
      server: 1879748453-hyn81.cn-beijing.nas.aliyuncs.com
      path: /pv-alertmanager-for-middleware

