apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-alertmanager-for-middleware
  namespace: monitoring 
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 100Gi

