metadata:
  name: apollo-adminservice-prod
  namespace: inc
  labels:
    wayne-app: apollo-adminservice
    wayne-ns: inc
    app: apollo-adminservice-prod
data:
  application-github.properties: >-
    spring.datasource.url=jdbc:mysql://db-host:3306/apolloconfigdb?characterEncoding=utf8

    spring.datasource.username=apollo

    spring.datasource.password=password

    spring.jpa.database-platform=org.hibernate.dialect.MySQL5Dialect

    eureka.service.url=http://apollo-configservice-prod/eureka/
