---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: skywalking-c0-oap
  labels:
    wayne-app: skywalking-c0
    wayne-ns: inc
    app: skywalking-c0-oap
spec:
  progressDeadlineSeconds: 600
  #生产配置，>1，根据实际情况。
  #replicas: 2
  #测试配置
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: skywalking-c0-oap
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: skywalking-c0-oap
        choerodon.io/infra: skywalking-c0-oap
        choerodon.io/release: skywalking-c0-oap
        wayne-app: skywalking-c0
        wayne-ns: inc
    spec:
      containers:
        - env:
            - name: SW_L0AD_CONFIG_FILE_FROM_VOLUME
              value: 'true'
            #生产配置，根据实际情况修改，原则是小资源多实例。
            #- name: JAVA_OPTS
            #  value: '-Xms6144M -Xmx6144M'
            #测试配置
            - name: JAVA_OPTS
              value: '-Xms1024M -Xmx1024M'
            - name: SKYWALKING_COLLECTOR_UID
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.uid
            #至关重要，必须保证agent与oap，ui的时区一致，否则UI不显示数据。根据各自公司的情况设置合适的时区。
            - name: TZ
              value: Asia/Shanghai
          image: 'apache/skywalking-oap-server:6.4.0'
          imagePullPolicy: IfNotPresent
          name: oap
          ports:
            - containerPort: 11800
              name: grpc
              protocol: TCP
            - containerPort: 12800
              name: rest
              protocol: TCP
          resources:
            #生产配置，根据实际情况修改，原则是小资源多实例。
            #limits:
            #  cpu: '1'
            #  memory: 8Gi
            #requests:
            #  memory: 8Gi
            #  cpu: '1'
            #测试配置
            limits:
              cpu: '1'
              memory: 2Gi
            requests:
              memory: 2Gi
              cpu: '0.1'
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /skywalking/config
              name: config
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - configMap:
            defaultMode: 420
            name: skywalking-c0-configmap
          name: config
