---
metadata:
  name: pro-apollo-configservice001
  labels:
    wayne-app: pro-apollo
    wayne-ns: inc
    app: pro-apollo-configservice001
  namespace: inc
spec:
  selector:
    wayne-app: apollo-configservice
  ports:
    - protocol: TCP
      targetPort: 8080
      port: 80
      name: pro-apollo-configservice001-80
  type: ClusterIP
apiVersion: v1
kind: Service

---
metadata:
  name: pro-apollo-configservice002
  labels:
    wayne-app: pro-apollo
    wayne-ns: inc
    app: pro-apollo-configservice002
  namespace: inc
spec:
  selector:
    wayne-app: apollo-configservice
  ports:
    - protocol: TCP
      targetPort: 8080
      port: 80
      name: pro-apollo-configservice002-80
  type: ClusterIP
apiVersion: v1
kind: Service

---
metadata:
  name: pro-apollo-configservice003
  labels:
    wayne-app: pro-apollo
    wayne-ns: inc
    app: pro-apollo-configservice003
  namespace: inc
spec:
  selector:
    wayne-app: apollo-configservice
  ports:
    - protocol: TCP
      targetPort: 8080
      port: 80
      name: pro-apollo-configservice003-80
  type: ClusterIP
apiVersion: v1
kind: Service
