---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: coohua
  name: redis-hkcmall
  labels:
    app: redis-hkcmall
data:
  fix-ip.sh: |
    #!/bin/sh
    REDIS_CONFIG="/data/redis.conf"
    cp /conf/redis.conf  /data/redis.conf
    if [ -f ${REDIS_CONFIG} ]; then
      if [ -z "${POD_IP}" ]; then 
        echo "Unable to determine Pod IP address!"
        exit 1
      fi
      echo "Updating my IP to ${POD_IP} in ${REDIS_CONFIG}"
      sed -i.bak -e "/bind/ s/[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}/${POD_IP}/" ${REDIS_CONFIG}
    fi
    exec "$@"
  redis.conf: |+
    port 6379
    bind 0.0.0.0
    maxmemory 500mb
    appendonly yes
    protected-mode no
---
apiVersion: v1
kind: Service
metadata:
  namespace: coohua
  name: redis-hkcmall
  labels:
    app: redis-hkcmall
spec:
  ports:
  - port: 6379
    name: redis-hkcmall
  clusterIP: None
  selector:
    app: redis-hkcmall
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: coohua
  name: redis-hkcmall
spec:
  serviceName: "redis-hkcmall"
  replicas: 1
  selector:
    matchLabels:
      app: redis-hkcmall
  template:
    metadata:
      labels:
        app: redis-hkcmall
    spec:
      containers:
      - name: redis-hkcmall
        image: redis:5.0-rc
        ports:
        - containerPort: 6379
          name: redis-hkcmall
        command: ["/conf/fix-ip.sh", "redis-server", "/data/redis.conf"]
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - "redis-cli -h $(hostname) -p 6379 ping"
          initialDelaySeconds: 15
          timeoutSeconds: 5
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - "redis-cli -h $(hostname) -p 6379 ping"
          initialDelaySeconds: 20
          periodSeconds: 3  
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        volumeMounts:
        - name: conf
          mountPath: /conf
          readOnly: false
        - name: data
          mountPath: /data
          readOnly: false
        resources:
          requests:
            cpu: 500m
            memory: 1500Mi
          limits:
            cpu: 500m
            memory: 1500Mi
      volumes:
      - name: conf
        configMap:
          name: redis-hkcmall
          defaultMode: 0755
  volumeClaimTemplates:
  - metadata:
      name: data
      labels:
        name: redis-hkcmall
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "managed-nfs-storage"
      resources:
        requests:
          storage: 5Gi


