---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: ingress-traefik
  name: traefik-ingress-controller

---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  namespace: ingress-traefik
  name: traefik
  labels:
    app: traefik

spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      serviceAccountName: traefik-ingress-controller
      containers:
        - name: traefik
          #image: traefik:v2.1.1
          image: traefik:v2.0
          args:
            - --api
            - --accesslog
            - --entrypoints.web.Address=:8000
            - --entrypoints.websecure.Address=:4443
            - --providers.kubernetescrd
            #- --providers.kubernetescrd.trace
            #- --certificatesresolvers.default.acme
            #- --certificatesresolvers.default.acme.acmelogging
            #- --certificatesresolvers.default.acme.tlschallenge
            #- --certificatesresolvers.default.acme.onhostrule
            #- --certificatesresolvers.default.acme.email=foo@you.com
            #- --certificatesresolvers.default.acme.entrypoint=websecure
            #- --certificatesresolvers.default.acme.storage=acme.json
            # Please note that this is the staging Let's Encrypt server.
            # Once you get things working, you should remove that whole line altogether.
            # 自动获取证书和更新
            #- --acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
          ports:
            - name: web
              containerPort: 8000
            - name: websecure
              containerPort: 4443
            - name: admin
              containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: ingress-traefik
spec:
  ports:
    - protocol: TCP
      name: web
      port: 8000
    - protocol: TCP
      name: admin
      port: 8080
    - protocol: TCP
      name: websecure
      port: 4443
  selector:
    app: traefik
