apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-local-es-min-c0-data0
  namespace: elasticsearch
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: "pv-local-es-min-c0-data"
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /datavip/k8s-data/pv-local-es-min-c0-data0
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - future
