apiVersion: v1
kind: PersistentVolume
metadata:
  name: rocketmq-c4-console-0
  namespace: inc
  labels:
    app: rocketmq-c4-console
    wayne-app: rocketmq-c4-console
    wayne-ns: inc
spec:
  capacity:
      storage: 10Gi
  mountOptions:
      - vers=4.0
      - noresvport
  accessModes:
      - ReadWriteMany
  storageClassName: "rocketmq-c4-console"
  persistentVolumeReclaimPolicy: Retain
  #表示使用本地存储
  local:
    path: /datavip/k8s-data/rocketmq-c4-console
  #生产使用阿里云的nas存储。
  #nfs:
  #  server: aliyun nas url
  #  path: /rocketmq-c4-console
