apiVersion: v1
kind: PersistentVolume
metadata:
  name: rocketmq-c4-namesrv-0
  namespace: inc
  labels:
    app: rocketmq-c4-namesrv
    wayne-app: rocketmq-c4-namesrv
    wayne-ns: inc
spec:
  capacity:
      storage: 20Gi
  mountOptions:
      - vers=4.0
      - noresvport
  accessModes:
      - ReadWriteOnce
  storageClassName: "rocketmq-c4-namesrv"
  persistentVolumeReclaimPolicy: Retain
  #表示使用本地存储
  local:
    path: /datavip/k8s-data/rocketmq-c4-namesrv-0
  #生产使用阿里云的nas存储。
  #nfs:
  #  server: aliyun nas url
  #  path: /rocketmq-c4-namesrv-0

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rocketmq-c4-namesrv-1
  namespace: inc
  labels:
    app: rocketmq-c4-namesrv
    wayne-app: rocketmq-c4-namesrv
    wayne-ns: inc
spec:
  capacity:
      storage: 20Gi
  mountOptions:
      - vers=4.0
      - noresvport
  accessModes:
      - ReadWriteOnce
  storageClassName: "rocketmq-c4-namesrv"
  persistentVolumeReclaimPolicy: Retain
  #表示使用本地存储
  local:
    path: /datavip/k8s-data/rocketmq-c4-namesrv-1
  #生产使用阿里云的nas存储。
  #nfs:
  #  server: aliyun nas url
  #  path: /rocketmq-c4-namesrv-1